name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_flags: "--config=.github/.golangci.yml"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
